# Generated by Django 3.2.9 on 2022-01-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
