# Generated by Django 3.2.9 on 2021-12-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211215_0131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
