# Generated by Django 3.2.9 on 2022-01-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_testimonial_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='changes_requested',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
